brew cask install filezilla
brew cask install iterm2
brew cask install google-chrome
brew cask install sourcetree
brew cask install sublime-text
brew cask install evernote
brew cask install toggldesktop
brew cask install 1password
brew cask install skype
brew cask install spectacle
brew cask install dropbox
brew cask install flux
brew cask install alfred
brew cask install appcleaner
brew cask install webstorm